/**
 * This class is generated by jOOQ
 */
package rfitzpatrick.dbz.DatabaseJOOQ.tables;


import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import rfitzpatrick.dbz.DatabaseJOOQ.Dbz;
import rfitzpatrick.dbz.DatabaseJOOQ.Keys;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.records.DbzCardlistRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbzCardlist extends TableImpl<DbzCardlistRecord> {

	private static final long serialVersionUID = 838383263;

	/**
	 * The reference instance of <code>dbz.dbz_cardlist</code>
	 */
	public static final DbzCardlist DBZ_CARDLIST = new DbzCardlist();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DbzCardlistRecord> getRecordType() {
		return DbzCardlistRecord.class;
	}

	/**
	 * The column <code>dbz.dbz_cardlist.id</code>.
	 */
	public final TableField<DbzCardlistRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>dbz.dbz_cardlist.name</code>.
	 */
	public final TableField<DbzCardlistRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>dbz.dbz_cardlist.set</code>.
	 */
	public final TableField<DbzCardlistRecord, String> SET = createField("set", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>dbz.dbz_cardlist.card level</code>.
	 */
	public final TableField<DbzCardlistRecord, String> CARD_LEVEL = createField("card level", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>dbz.dbz_cardlist.Number</code>.
	 */
	public final TableField<DbzCardlistRecord, String> NUMBER = createField("Number", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>dbz.dbz_cardlist.Style</code>.
	 */
	public final TableField<DbzCardlistRecord, String> STYLE = createField("Style", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>dbz.dbz_cardlist.Rarity</code>.
	 */
	public final TableField<DbzCardlistRecord, String> RARITY = createField("Rarity", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>dbz.dbz_cardlist.Type</code>.
	 */
	public final TableField<DbzCardlistRecord, String> TYPE = createField("Type", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>dbz.dbz_cardlist.imgUrl</code>.
	 */
	public final TableField<DbzCardlistRecord, String> IMGURL = createField("imgUrl", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * Create a <code>dbz.dbz_cardlist</code> table reference
	 */
	public DbzCardlist() {
		this("dbz_cardlist", null);
	}

	/**
	 * Create an aliased <code>dbz.dbz_cardlist</code> table reference
	 */
	public DbzCardlist(String alias) {
		this(alias, DBZ_CARDLIST);
	}

	private DbzCardlist(String alias, Table<DbzCardlistRecord> aliased) {
		this(alias, aliased, null);
	}

	private DbzCardlist(String alias, Table<DbzCardlistRecord> aliased, Field<?>[] parameters) {
		super(alias, Dbz.DBZ, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<DbzCardlistRecord> getPrimaryKey() {
		return Keys.KEY_DBZ_CARDLIST_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<DbzCardlistRecord>> getKeys() {
		return Arrays.<UniqueKey<DbzCardlistRecord>>asList(Keys.KEY_DBZ_CARDLIST_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlist as(String alias) {
		return new DbzCardlist(alias, this);
	}

	/**
	 * Rename this table
	 */
	public DbzCardlist rename(String name) {
		return new DbzCardlist(name, null);
	}
}
