/**
 * This class is generated by jOOQ
 */
package rfitzpatrick.dbz.DatabaseJOOQ.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzCardlist;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbzCardlistRecord extends UpdatableRecordImpl<DbzCardlistRecord> implements Record9<Integer, String, String, String, String, String, String, String, String> {

	private static final long serialVersionUID = -284351433;

	/**
	 * Setter for <code>dbz.dbz_cardlist.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dbz.dbz_cardlist.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>dbz.dbz_cardlist.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dbz.dbz_cardlist.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>dbz.dbz_cardlist.set</code>.
	 */
	public void setSet(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dbz.dbz_cardlist.set</code>.
	 */
	public String getSet() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>dbz.dbz_cardlist.card level</code>.
	 */
	public void setCardLevel(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dbz.dbz_cardlist.card level</code>.
	 */
	public String getCardLevel() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>dbz.dbz_cardlist.Number</code>.
	 */
	public void setNumber(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dbz.dbz_cardlist.Number</code>.
	 */
	public String getNumber() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>dbz.dbz_cardlist.Style</code>.
	 */
	public void setStyle(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dbz.dbz_cardlist.Style</code>.
	 */
	public String getStyle() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>dbz.dbz_cardlist.Rarity</code>.
	 */
	public void setRarity(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>dbz.dbz_cardlist.Rarity</code>.
	 */
	public String getRarity() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>dbz.dbz_cardlist.Type</code>.
	 */
	public void setType(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>dbz.dbz_cardlist.Type</code>.
	 */
	public String getType() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>dbz.dbz_cardlist.imgUrl</code>.
	 */
	public void setImgurl(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>dbz.dbz_cardlist.imgUrl</code>.
	 */
	public String getImgurl() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, String, String, String, String, String, String, String, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, String, String, String, String, String, String, String, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return DbzCardlist.DBZ_CARDLIST.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return DbzCardlist.DBZ_CARDLIST.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return DbzCardlist.DBZ_CARDLIST.SET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return DbzCardlist.DBZ_CARDLIST.CARD_LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return DbzCardlist.DBZ_CARDLIST.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return DbzCardlist.DBZ_CARDLIST.STYLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return DbzCardlist.DBZ_CARDLIST.RARITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return DbzCardlist.DBZ_CARDLIST.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return DbzCardlist.DBZ_CARDLIST.IMGURL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSet();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getCardLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getStyle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getRarity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getImgurl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord value3(String value) {
		setSet(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord value4(String value) {
		setCardLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord value5(String value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord value6(String value) {
		setStyle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord value7(String value) {
		setRarity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord value8(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord value9(String value) {
		setImgurl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbzCardlistRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DbzCardlistRecord
	 */
	public DbzCardlistRecord() {
		super(DbzCardlist.DBZ_CARDLIST);
	}

	/**
	 * Create a detached, initialised DbzCardlistRecord
	 */
	public DbzCardlistRecord(Integer id, String name, String set, String cardLevel, Integer number, String style, String rarity, String type, String imgurl) {
		super(DbzCardlist.DBZ_CARDLIST);

		setValue(0, id);
		setValue(1, name);
		setValue(2, set);
		setValue(3, cardLevel);
		setValue(4, number);
		setValue(5, style);
		setValue(6, rarity);
		setValue(7, type);
		setValue(8, imgurl);
	}
}
