/**
 * This class is generated by jOOQ
 */
package rfitzpatrick.dbz.DatabaseJOOQ;


import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzCardlist;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzDecks;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzPrices;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dbz extends SchemaImpl {

	private static final long serialVersionUID = 146604808;

	/**
	 * The reference instance of <code>dbz</code>
	 */
	public static final Dbz DBZ = new Dbz();

	/**
	 * No further instances allowed
	 */
	private Dbz() {
		super("dbz");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			DbzCardlist.DBZ_CARDLIST,
			DbzDecks.DBZ_DECKS,
			DbzPrices.DBZ_PRICES);
	}
}
