/**
 * This class is generated by jOOQ
 */
package rfitzpatrick.dbz.DatabaseJOOQ;


import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzCardlist;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzDecks;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzPrices;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.records.DbzCardlistRecord;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.records.DbzDecksRecord;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.records.DbzPricesRecord;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>dbz</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<DbzCardlistRecord, Integer> IDENTITY_DBZ_CARDLIST = Identities0.IDENTITY_DBZ_CARDLIST;
	public static final Identity<DbzDecksRecord, Integer> IDENTITY_DBZ_DECKS = Identities0.IDENTITY_DBZ_DECKS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<DbzCardlistRecord> KEY_DBZ_CARDLIST_PRIMARY = UniqueKeys0.KEY_DBZ_CARDLIST_PRIMARY;
	public static final UniqueKey<DbzDecksRecord> KEY_DBZ_DECKS_PRIMARY = UniqueKeys0.KEY_DBZ_DECKS_PRIMARY;
	public static final UniqueKey<DbzPricesRecord> KEY_DBZ_PRICES_PRIMARY = UniqueKeys0.KEY_DBZ_PRICES_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<DbzCardlistRecord, Integer> IDENTITY_DBZ_CARDLIST = createIdentity(DbzCardlist.DBZ_CARDLIST, DbzCardlist.DBZ_CARDLIST.ID);
		public static Identity<DbzDecksRecord, Integer> IDENTITY_DBZ_DECKS = createIdentity(DbzDecks.DBZ_DECKS, DbzDecks.DBZ_DECKS.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<DbzCardlistRecord> KEY_DBZ_CARDLIST_PRIMARY = createUniqueKey(DbzCardlist.DBZ_CARDLIST, DbzCardlist.DBZ_CARDLIST.ID);
		public static final UniqueKey<DbzDecksRecord> KEY_DBZ_DECKS_PRIMARY = createUniqueKey(DbzDecks.DBZ_DECKS, DbzDecks.DBZ_DECKS.ID);
		public static final UniqueKey<DbzPricesRecord> KEY_DBZ_PRICES_PRIMARY = createUniqueKey(DbzPrices.DBZ_PRICES, DbzPrices.DBZ_PRICES.ID);
	}
}
