/**
 * This class is generated by jOOQ
 */
package rfitzpatrick.dbz.DatabaseJOOQ;


import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzCardlist;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzDecks;
import rfitzpatrick.dbz.DatabaseJOOQ.tables.DbzPrices;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dbz
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table dbz.dbz_cardlist
	 */
	public static final DbzCardlist DBZ_CARDLIST = DbzCardlist.DBZ_CARDLIST;

	/**
	 * The table dbz.dbz_decks
	 */
	public static final DbzDecks DBZ_DECKS = DbzDecks.DBZ_DECKS;

	/**
	 * The table dbz.dbz_prices
	 */
	public static final DbzPrices DBZ_PRICES = DbzPrices.DBZ_PRICES;
}
